# Generated by Django 4.2.10 on 2025-04-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(default=None),
        ),
    ]
